/**
 * English Example for Vivox Node.js Wrapper
 * 
 * This script demonstrates the basic flow:
 * 1. Initialization
 * 2. Event Handling
 * 3. Connection & Login
 */

const vivox = require('./index');
const { VivoxUtils, VivoxError } = require('./index');

// Constants (Replace with your actual data)
const SERVER_URL = "https://example.vivox.com/app";
const DOMAIN = "example.vivox.com";
const ENV_DOMAIN = "v98.vivox.com";
const USER_ID = "test_user_01";
const CHANNEL_ID = "lobby_room";

// Tokens must be generated by your secure back-end
const LOGIN_TOKEN = "YOUR_LOGIN_TOKEN";
const CHANNEL_TOKEN = "YOUR_CHANNEL_TOKEN";

const accountUri = VivoxUtils.generateAccountUri(DOMAIN, USER_ID, ENV_DOMAIN);
const channelUri = VivoxUtils.generateChannelUri(DOMAIN, CHANNEL_ID, ENV_DOMAIN);
const connectorHandle = "main_connector";

console.log('Using Vivox SDK:', vivox.getVersion());

// --- Setup Event Listeners ---

vivox.on('connectorCreated', (event) => {
    if (event.status === VivoxError.VX_E_SUCCESS) {
        console.log('Connector created. Attempting login...');
        vivox.loginAnonymous(connectorHandle, accountUri, LOGIN_TOKEN);
    } else {
        console.error(`Connector error: ${event.status_name}`);
    }
});

vivox.on('loginSuccess', (event) => {
    console.log('Logged in successfully. Joining channel...');
    vivox.joinChannel(accountUri, channelUri, CHANNEL_TOKEN);
});

vivox.on('joinSuccess', (event) => {
    console.log('Joined channel:', channelUri);
    
    // Set local volumes
    vivox.setLocalMicVolume(100);
    vivox.setLocalSpeakerVolume(80);

    // Send a test message after 2 seconds
    const sessHandle = VivoxUtils.generateSessionHandle(channelUri);
    setTimeout(() => {
        vivox.sendMessage(sessHandle, "Hello from the new Node.js wrapper!");
    }, 2000);
});

vivox.on('participantAdded', (p) => {
    console.log(`[USER JOINED] ${p.participant_uri}`);
});

vivox.on('message', (m) => {
    console.log(`[MSG] ${m.participant_uri}: ${m.message}`);
});

// --- Start the process ---

const initStatus = vivox.initialize();
if (initStatus === 0) {
    console.log('SDK Initialized.');
    vivox.connectorCreate(SERVER_URL, connectorHandle);
} else {
    console.error('Failed to initialize SDK. Code:', initStatus);
}

// Keep the process alive for 30 seconds
setTimeout(() => {
    console.log('Shutting down...');
    vivox.uninitialize();
    process.exit(0);
}, 30000);
